volumes:

  common-sonarqube-data:
    name: 'common-sonarqube-data'
  common-sonarqube-extensions:
    name: 'common-sonarqube-extensions'
  common-sonarqube-logs:
    name: 'common-sonarqube-logs'

services:

  sonarqube:
    image: sonarqube:${SONARQUBE_IMAGE_TAG:-26.7.0.124771-community}
    env_file:
      - .envs/sonarqube.env
    networks:
      common-net:
        aliases:
          - common-sonarqube
    volumes:
      - common-sonarqube-data:/opt/sonarqube/data
      - common-sonarqube-extensions:/opt/sonarqube/extensions
      - common-sonarqube-logs:/opt/sonarqube/logs
    stop_grace_period: 3600s
    restart: unless-stopped
